export const KEYWORDS = {
  virtualTours: [
    "360 Virtual Tours Saudi Arabia",
    "Virtual Tour Company Riyadh",
    "Real Estate Virtual Tours Saudi Arabia",
    "Hotel Virtual Tours Saudi Arabia",
    "Construction Virtual Tours Saudi Arabia",
    "Digital Twin Saudi Arabia",
    "Google Street View Saudi Arabia",
    "360 degree tour KSA",
  ],
  virtualToursAr: [
    "جولات افتراضية 360 درجة",
    "جولات افتراضية الرياض",
    "شركة جولات افتراضية",
    "جولات افتراضية للفنادق",
    "جولات افتراضية للمستشفيات",
    "جولات افتراضية للعقارات",
    "التوأم الرقمي",
    "التوأم الرقمي للمشاريع",
    "حلول التوأم الرقمي",
  ],
  webDevelopment: [
    "Website Development Saudi Arabia",
    "Web Design Riyadh",
    "Web Development Riyadh",
    "Ecommerce Development Saudi Arabia",
    "Mobile App Development Saudi Arabia",
    "Business Automation Saudi Arabia",
  ],
  webDevelopmentAr: [
    "تطوير مواقع إلكترونية",
    "تصميم مواقع إلكترونية",
    "تطوير مواقع الرياض",
    "تصميم مواقع جدة",
    "بناء موقع إلكتروني السعودية",
    "تطوير تطبيقات جوال السعودية",
  ],
  ai: [
    "AI Solutions Saudi Arabia",
    "AI Development Riyadh",
    "AI Automation Saudi Arabia",
    "AI Chatbots Saudi Arabia",
    "Arabic AI Chatbot Saudi Arabia",
  ],
  aiAr: [
    "الذكاء الاصطناعي للشركات",
    "حلول الذكاء الاصطناعي",
    "روبوتات المحادثة الذكية",
    "أتمتة الأعمال بالذكاء الاصطناعي",
    "الذكاء الاصطناعي الرياض",
    "الذكاء الاصطناعي جدة",
  ],
  erp: [
    "ERP Solutions Saudi Arabia",
    "SAP Implementation Saudi Arabia",
    "SAP Solutions Saudi Arabia",
    "Workflow Automation Saudi Arabia",
    "Digital Transformation Saudi Arabia",
  ],
  erpAr: [
    "حلول ERP",
    "أنظمة SAP",
    "أتمتة الأعمال",
    "حلول ERP الرياض",
    "تطبيق SAP السعودية",
    "التحول الرقمي السعودية",
  ],
  riyadh: [
    "Riyadh virtual tours",
    "Riyadh web development",
    "Riyadh AI solutions",
    "Riyadh ERP SAP",
  ],
  riyadhAr: [
    "جولات افتراضية الرياض",
    "تطوير مواقع الرياض",
    "حلول الذكاء الاصطناعي الرياض",
    "ERP وSAP الرياض",
  ],
};
