export const SEO_CONFIG = {
  siteName: "X360",
  siteUrl: "https://www.x-360.ai",
  defaultTitle: "360 Virtual Tours Saudi Arabia | Web Development, AI & ERP Solutions | X360",
  defaultDescription: "شركة X360 الرائدة في السعودية تقدم خدمات الجولات الافتراضية 360 درجة، التوأم الرقمي، تطوير المواقع الإلكترونية، حلول الذكاء الاصطناعي وأنظمة ERP وSAP للشركات والمؤسسات في الرياض وجدة وجميع أنحاء المملكة.",
  defaultOgImage: "https://www.x-360.ai/opengraph.jpg",
  twitterHandle: "@x360sa",
  contact: {
    email: "info@x-360.ai",
    phone: "+966532087436",
    address: "Riyadh, Saudi Arabia",
    whatsapp: "+966532087436",
  },
  social: {
    twitter: "https://twitter.com/x360sa",
    instagram: "https://instagram.com/x360sa",
    linkedin: "https://linkedin.com/company/x360sa",
    youtube: "https://youtube.com/@x360sa",
  },
  targetRegion: "SA",
  targetCountry: "Saudi Arabia",
  services: [
    "360 Virtual Tours",
    "Digital Twins",
    "Virtual Reality (VR)",
    "Augmented Reality (AR)",
    "Website Development",
    "Mobile App Development",
    "AI Solutions",
    "AI Automation",
    "AI Chatbots",
    "ERP Solutions",
    "SAP Solutions",
    "Workflow Automation",
    "Business Intelligence",
    "Enterprise Software Development",
  ],
};
export type SeoConfig = typeof SEO_CONFIG;
